### ISSUE TITLE
No screen found on a laptop

### ISSUE THREAD

**Issue by 29jm** [zee-mzha/vibrantLinux#2]
Hey! First of thank you for this project, it's super useful!

I'm on a laptop with a dedicated nvidia card, and I use nvidia-xrun when I want to use it.  
In this context, running `nvidia-settings -q dpys` returns
```
1 Display Device on arch:1

    [0] arch:1[dpy:0] (HDMI-0)

      Has the following names:
        DFP
        DFP-0
        DPY-0
        HDMI-0
```

Looking at the code, it's grepping for "connected" which isn't found here. I don't know what a desktop output looks like but perhaps pattern matching (something like this `\[\d+\] .+:\d+\[.+:.+\]` adapted to grep perhaps) would be more reliable? I'll make a PR sometimes next week if you're ok with that!

**Comment by zee-mzha** [comment]
Oh wow, I guess that's downside of only analyzing the output on my own machine! This is what it looks like on my end FYI
    
    8 Display Devices on zeeDT:0

    [0] zeeDT:0[dpy:0] (DVI-D-0) (connected, enabled)

      Has the following names:
        DFP
        DFP-0
        DPY-EDID-4cab3c6f-c9ee-db12-f037-d26dacd135e3
        DPY-0
        DVI-D-0
    ...

Anyways, thank you very much for reporting this, I'll fix it in just a second so no need to make a PR. If I'm being honest using grep was already stupid since Qt has it's own regex, but I think even that is a little overkill for this problem. It seems that the lines the program is interested in are the only ones that contain a "[" and "]" characters so I'll probably replace the existing search with this instead

    QProcess nvidia;
    nvidia.start("nvidia-settings -q dpys");
    nvidia.waitForFinished();

    QStringList res = QString(nvidia.readAll()).split("\n").filter("[");

I'm going to go ahead and test this, and if it works as expected then I'll push the change, if not then I'll use the regex option. Thank you for reporting this!

**Comment by 29jm** [comment]
Perhaps grepping for connected first, and use the result if there's a match, otherwise use the first line matching the pattern?  
I can't test right now but I guess if I plugged in an external monitor I would get the `(connected, enabled)` part too, and it would work there as well.

**Comment by zee-mzha** [comment]
I might add a "refresh displays" or "reload displays" button instead that will allow you update your list of screens at any given time.

**Comment by 29jm** [comment]
That sounds like a great solution! Thank you for looking at this issue.

**Comment by 29jm** [comment]
Bad news, `nvidia-settings -q [HDMI-0]/DigitalVibrance` just prints two newlines on my end...  
Investigating a bit, the nvidia panel says "PRIME displays cannot be controlled by nvidia-settings and must be configured by an external RandR capable tool. The display is shown in the layout window for information purposes only".

I guess this is over for vibrance and nvidia-xrun. Just to be sure, I'll try vibrantLinux with my card as primary, disabling intel, see how it goes and if a change is still necessary.

**Comment by zee-mzha** [comment]
That's good to know, thank you for the update. Looking forward to hearing more.

**Comment by 29jm** [comment]
> I'll try vibrantLinux with my card as primary, disabling intel, see how it goes and if a change is still necessary.

I couldn't get that to work, getting a black screen and a complete freeze on boot... optimus is such a mess. Apparently using only the card also uses the PRIME mechanism, so I would've had the same issue, probably.
