### ISSUE TITLE
Feature Request: Hide Window at Start-Up

### ISSUE THREAD

**Issue by maxfrei750** [zee-mzha/vibrantLinux#22]
First of all: Thanks for the awesome application.

It would be great if it was possible to tick a check box in the settings to have the application being started in the background, if autostarting is enabled.

**Comment by guihkx** [comment]
It should already do that, by default. Check the `vibrantLinux.desktop` file inside `~/.config/autostart`:

```
$ cat ~/.config/autostart/vibrantLinux.desktop
[Desktop Entry]
Version=1.0
Name=Vibrant Linux
GenericName=Digital vibrance controller
Comment=Program-specific digital vibrance controller
Exec=/usr/bin/vibrantLinux --hidden
Icon=vibrantLinux
Terminal=false
Type=Application
Categories=Utility;
```

Notice the `Exec=` section, which passes `--hidden` to Vibrant Linux, so it can start 'minimized' to system tray.

If you're on GNOME, though, I'm not entirely sure what the behavior will be, since GNOME doesn't come with an integrated system tray...

**Comment by zee-mzha** [comment]
no updates for a while and the --hidden option is there. Closing this for now
