### ISSUE TITLE
The "Set vibrance only when program is in focus" option is not saved in the config file

### ISSUE THREAD

**Issue by guihkx** [zee-mzha/vibrantLinux#24]
Hi,

I don't know if this is intentional, but the **"Set vibrance only when program is in focus"** option resets after you close Vibrant Linux. And looking at Vibrant Linux's config file, I couldn't find any property related to that feature as well.

Thanks.

**Comment by zee-mzha** [comment]
I'll add this in the next version release, shouldnt be too hard to implement (also yay we get to use the config version variable now!)

**Comment by zee-mzha** [comment]
dang it I keep doing that

**Comment by zee-mzha** [comment]
I'll push the change later tonight, sorry this has taken so long. Unfortunately due to compatibility with software that's necessary for school, as well as for some of the hardware im running I've been forced to switch to windows 10. This will cause the project's development to grind to a halt at least as far as contributions from me are concerned. I'm not sure where else to post this but unless someone would like to step up im afraid v2.1.6 will be the last update for a while.

**Comment by zee-mzha** [comment]
changes pushed :)
